#!/bin/bash

################################################################
# @ VERSION     0.0.1
# @ AUTHOR      John Yoon
#
# Usage: initial_setup
# Returns:
#   0 on success
#   1 on error
################################################################




